### ISSUE TITLE
daemon.warn cuxd with new version

### ISSUE THREAD

**Issue by roe1974** [hobbyquaker/homematic-manager#104]
Hi

Using the new version i got this in the log.....is that normal ?

regards, Richard

Dec  8 20:28:14 homematic-raspi daemon.warn cuxd[7108]: process_rpc_request(192.168.10.174) - illegal XMLRPC(init) request
Dec  8 20:28:28 homematic-raspi daemon.warn cuxd[7108]: process_rpc_request(192.168.10.174) - illegal XMLRPC(init) request
Dec  8 20:30:07 homematic-raspi daemon.warn cuxd[7108]: process_rpc_request(192.168.10.174) - illegal XMLRPC(init) request
Dec  8 20:30:51 homematic-raspi daemon.warn cuxd[7108]: process_rpc_request(192.168.10.174) - illegal XMLRPC(ping) request
Dec  8 20:31:07 homematic-raspi daemon.warn cuxd[7108]: process_rpc_request(192.168.10.174) - illegal XMLRPC(ping) request
Dec  8 20:31:22 homematic-raspi daemon.warn cuxd[7108]: process_rpc_request(192.168.10.174) - illegal XMLRPC(init) request
Dec  8 20:31:35 homematic-raspi daemon.warn cuxd[7108]: process_rpc_request(192.168.10.174) - illegal XMLRPC(init) request
Dec  8 20:32:32 homematic-raspi daemon.warn cuxd[7108]: process_rpc_request(192.168.10.174) - illegal XMLRPC(init) request
Dec  8 20:32:47 homematic-raspi daemon.warn cuxd[7108]: process_rpc_request(192.168.10.174) - illegal XMLRPC(init) request

**Comment by hobbyquaker** [comment]
Same root cause as #111
