### ISSUE TITLE
CUxD Geräte werden nicht angezeigt

### ISSUE THREAD

**Issue by bkrautter** [hobbyquaker/homematic-manager#111]
Im Homematic Manger Version 2.3.0 werden bei mir die CUxD Geräte nicht mehr angezeigt.
Liegt es an der Kombination mit RaspberryMatic 3.41.11.20190126 ?
Habe bereits die Firewall Regeln überprüft. Gibt es noch weitere Port Eingaben. Welche?

**Comment by FraatRamski** [comment]
Das gleiche bei mir. Raspi 3.41.11.20190126, Manager 2.3. 
Info: Im Iobroker werden bei mir alle CUxD Geräte angezeigt.

**Comment by finerider** [comment]
So sieht es bei mir mit einer CCU2 und CUxD - jeweils aktuelle Firmare - auch aus.
