### ISSUE TITLE
homematic-manager zeigt nur "Ladevorgang" an und verbindet sich nicht mit homematic

### ISSUE THREAD

**Issue by JeWi81** [hobbyquaker/homematic-manager#114]
Hallo,

ich habe folgendes Problem, bei dem ich für Hilfe dankbar bin:
Nach dem Starten des homematic-managers (hma) wird anscheinend keine Verbindung zum home assistant hergestellt. Gehe davon aus, weil ich oben rechts bei der IP-Adresse einen grünen Haken erwarten würde.

![image](https://user-images.githubusercontent.com/49509630/55934043-aef4ae00-5c2f-11e9-8074-530351af1043.png)

In der hma Konfiguration stimmt die IP-Adresse von PC und home assistent überein.
![image](https://user-images.githubusercontent.com/49509630/55934208-2de9e680-5c30-11e9-87f2-8e0366c0603e.png)
Router-screenshot

![image](https://user-images.githubusercontent.com/49509630/55934244-40642000-5c30-11e9-9b50-4a6c679a5a56.png)
hma-screenshot

Woran kann das liegen? Oder wenn hier noch Analysedaten fehlen (z.B. log Messages), dann bin ich gerne bereit diese zu liefern, bräuchte dazu einen Hinweis was zu machen wäre.

Vielen Dank im Voraus,

Jens

Rahmendaten:
hma version 2.5
home assistant:
![image](https://user-images.githubusercontent.com/49509630/55934394-b4062d00-5c30-11e9-8ffd-40d07d0586ec.png)

Add-on war gestartet
![image](https://user-images.githubusercontent.com/49509630/55934440-d1d39200-5c30-11e9-99df-e59c4b3fe9f3.png)

**Comment by widmann-it** [comment]
Gleiches Problem bei mir, Raspymatic (3.45.5.20190330)  Nach einer Wartzezeit von 10 Min. kommt die Fehlermeldung Unhandled Error  / Error:listen EADDRINUSE 0.0.0.:2000

**Comment by hobbyquaker** [comment]
Unter Windows liegt das vermutlich einfach an der Windows Firewall. Da der Hm-Manager nicht nur ausgehende Verbindungen nutzt sondern auch selbst RPC Server Ports für eingehende Verbindungen öffnet muss man da soweit ich weiss manuell ne Erlaubnis/Ausnahme setzen

**Comment by harabeck** [comment]
Ich habe das gleiche Problem. Ab Homemativ Manager Version **2.3.0** bekomme ich unter Windows 10 keine Datenübertragung zum BidCosRF. Ein grüner Haken ist gesetzt, aber der Ladevorgang kommt nicht zum Ende. Deinstallieren und Version 2.2.0 funktioniert sofort.

Woran kan das liegen?

**Comment by JeWi81** [comment]
Vielen Dank für die Info. Nutze Windows 7 mit Zugriffrecht Administrator. Beim Starten des Homematic Managers 2.5.0 popt stets folgendes Fenster hoch:

![image](https://user-images.githubusercontent.com/49509630/69916682-411b2200-145e-11ea-8684-dfc492802fc3.png)

Ich klicke dann mit der Einstellung im Fenster auf "Zugriff zulassen". Anschließend ist das Problem gelöst.
