### ISSUE TITLE
Name columns are not usable

### ISSUE THREAD

**Issue by jwiesel** [hobbyquaker/homematic-manager#117]
Hi,
first of all thanks for providing this nice tool! It saved me a lot of time creating new device links already.

My issue: The name columns in Homematic Manager do not show any content. Furthermore, if I want to set new names, they are not transferred to my CCU. It feels link the name columns are not correctly mapped from the frontend to the backend.
Specifically the following columns are empty:
* Devices > Name
* Links > SENDER Name
* Links > RECEIVER Name
* RSSI > Name
* Service Messages > Name
* Events > Name

My setup:
* Installed Homematic Manager version 2.5.0 with the .deb package on Ubuntu 19.04
* On startup I did not check "Hide name columns" as I want to use these columns
* RaspberryMatic version 3.47.18.20190918 running on a raspberry pi 3b

If you need further details, please let me know.

**Comment by hobbyquaker** [comment]
possibly this is caused by activated authentication on the ccu. hm-manager does not (yet) support auth

**Comment by hobbyquaker** [comment]
auth is now supported
