### ISSUE TITLE
Geräte anlernen

### ISSUE THREAD

**Issue by fortschritt311** [hobbyquaker/homematic-manager#32]
Hi.
Hab Hmcon(rfd) und den HM Manager jetzt am laufen. Lief alles Problemlos durch.

Jetzt habe ich das Problem das ich keine Geräte anlernen kann. Wenn ich den Anlernmodus 60s aktiviere findet er meinen Funk-Dreh-Fensterkontakt nicht. Auch über die Seriennummer hatte ich keinen Erfolg.
Gibts da noch nen Trick?

Gruß Maik

**Comment by hobbyquaker** [comment]
Hallo Maik,

Batteriegeräte kann man nicht über Seriennummer anlernen, das geht üblicherweise nur mit denen die mit Netzspannung versorgt werden.
Warum das anlernen fehlschlägt ist (wenn wir Glück haben) aus dem Logfile des rfd ersichtlich. Kannst Du das mal pasten? (/opt/hmcon/var/log/rfd.log)

Grüße
Sebastian

**Comment by fortschritt311** [comment]
Hallo Sebastian,

Hab es kurzerhand hier : http://workupload.com/file/7iq8mSKe hochgeladen. Es wäre für den Issue zu groß.

Gruß Maik

**Comment by fortschritt311** [comment]
So hab noch mal mit einem Thermostat HM-CC-TC probiert.
Er scheint es lt. Log-File zu finden nur irgendwie schlägt dann was fehl :
Spez. der Eintrag :  "Peering with JEQ0081328 failed"

<code>2015/07/19 13:51:57.961 <Debug> Entering install mode for 60 s
2015/07/19 13:52:06.459 <Debug> JEQ0081328's type is HM-CC-TC
2015/07/19 13:52:06.473 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:52:06.484 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:52:06.495 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:52:06.505 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:52:06.515 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:52:06.526 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:52:06.537 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:52:06.548 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:52:06.548 <Debug> Device firmware version is 2.1
2015/07/19 13:52:06.549 <Debug> TX:  @2787649685 0x266489 -> 0x1B1894 CONFIG_START [KEQ1066722]:
  CNT=1,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01
  CONFIG_CHANNEL = 0
  CONFIG_PEER_ADDRESS = 0x000000
  CONFIG_PEER_CHANNEL = 0
  CONFIG_PARAM_LIST = 0

2015/07/19 13:52:06.585 <Debug> (KEQ1066722) Response status: Telegram sent successfully.
2015/07/19 13:52:07.549 <Debug> SendFrame failed 1 times:  @2787649685 0x266489 -> 0x1B1894 CONFIG_START [KEQ1066722]:
  CNT=1,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01
  CONFIG_CHANNEL = 0
  CONFIG_PEER_ADDRESS = 0x000000
  CONFIG_PEER_CHANNEL = 0
  CONFIG_PARAM_LIST = 0

2015/07/19 13:52:07.549 <Warning> Peering with JEQ0081328 failed
2015/07/19 13:52:07.557 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:52:07.557 <Debug> Deleting persistent data for device JEQ0081328
2015/07/19 13:52:50.159 <Debug> LGWPortWrapper::bidcosChannelKeepAliveThreadFunction(): Checking connection.
2015/07/19 13:52:58.021 <Debug> (KEQ1066722) Response status: OK.
2015/07/19 13:52:58.021 <Debug> Leaving install mode.
2015/07/19 13:53:25.952 <Debug> Entering install mode for 60 s
2015/07/19 13:53:38.166 <Debug> LGWPortWrapper::bidcosChannelKeepAliveThreadFunction(): Checking connection.
2015/07/19 13:53:44.010 <Debug> JEQ0081328's type is HM-CC-TC
2015/07/19 13:53:44.020 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:53:44.031 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:53:44.042 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:53:44.051 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:53:44.062 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:53:44.073 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:53:44.084 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:53:44.095 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:53:44.095 <Debug> Device firmware version is 2.1
2015/07/19 13:53:44.095 <Debug> TX:  @2787747231 0x266489 -> 0x1B1894 CONFIG_START [KEQ1066722]:
  CNT=1,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01
  CONFIG_CHANNEL = 0
  CONFIG_PEER_ADDRESS = 0x000000
  CONFIG_PEER_CHANNEL = 0
  CONFIG_PARAM_LIST = 0

2015/07/19 13:53:44.131 <Debug> (KEQ1066722) Response status: Telegram sent successfully.
2015/07/19 13:53:45.095 <Debug> SendFrame failed 1 times:  @2787747231 0x266489 -> 0x1B1894 CONFIG_START [KEQ1066722]:
  CNT=1,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01
  CONFIG_CHANNEL = 0
  CONFIG_PEER_ADDRESS = 0x000000
  CONFIG_PEER_CHANNEL = 0
  CONFIG_PARAM_LIST = 0

2015/07/19 13:53:45.095 <Warning> Peering with JEQ0081328 failed
2015/07/19 13:53:45.103 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:53:45.103 <Debug> Deleting persistent data for device JEQ0081328
2015/07/19 13:54:11.645 <Debug> JEQ0081328's type is HM-CC-TC
2015/07/19 13:54:11.655 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:54:11.666 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:54:11.677 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:54:11.686 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:54:11.697 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:54:11.708 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:54:11.719 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:54:11.730 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:54:11.730 <Debug> Device firmware version is 2.1
2015/07/19 13:54:11.730 <Debug> TX:  @2787774867 0x266489 -> 0x1B1894 CONFIG_START [KEQ1066722]:
  CNT=1,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01
  CONFIG_CHANNEL = 0
  CONFIG_PEER_ADDRESS = 0x000000
  CONFIG_PEER_CHANNEL = 0
  CONFIG_PARAM_LIST = 0

2015/07/19 13:54:11.766 <Debug> (KEQ1066722) Response status: Telegram sent successfully.
2015/07/19 13:54:12.731 <Debug> SendFrame failed 1 times:  @2787774867 0x266489 -> 0x1B1894 CONFIG_START [KEQ1066722]:
  CNT=1,RPTEN=1,RPTED=0,BIDI=1,BURST=0,WAKEUP=0,WAKEMEUP=0,BCAST=0,TYPE=0x01
  CONFIG_CHANNEL = 0
  CONFIG_PEER_ADDRESS = 0x000000
  CONFIG_PEER_CHANNEL = 0
  CONFIG_PARAM_LIST = 0

2015/07/19 13:54:12.731 <Warning> Peering with JEQ0081328 failed
2015/07/19 13:54:12.739 <Debug> (KEQ1066722) Response status: OK, Data.
2015/07/19 13:54:12.739 <Debug> Deleting persistent data for device JEQ0081328
2015/07/19 13:54:25.972 <Debug> (KEQ1066722) Response status: OK.
2015/07/19 13:54:25.972 <Debug> Leaving install mode.
2015/07/19 13:54:58.174 <Debug> LGWPortWrapper::bidcosChannelKeepAliveThreadFunction(): Checking connection.
2015/07/19 13:55:30.181 <Debug> LGWPortWrapper::bidcosChannelKeepAliveThreadFunction(): Checking connection.
2015/07/19 13:56:02.188 <Debug> LGWPortWrapper::bidcosChannelKeepAliveThreadFunction(): Checking connection.
2015/07/19 13:56:34.195 <Debug> LGWPortWrapper::bidcosChannelKeepAliveThreadFunction(): Checking connection.
2015/07/19 13:57:06.203 <Debug> LGWPortWrapper::bidcosChannelKeepAliveThreadFunction(): Checking connection.
2015/07/19 13:57:38.210 <Debug> LGWPortWrapper::bidcosChannelKeepAliveThreadFunction(): Checking connection.</code>

**Comment by fortschritt311** [comment]
Was mir eben noch aufgefallen ist : 
Im hm-manager hat der HM-LGW-Lan Adapter die Firmware 1.13 während im rdf.log die Firmware 1.14 angezeigt wird.

**Comment by fortschritt311** [comment]
Ich hab noch nen bissel rumprobiert.
Der Hm-Manager läuft mit meiner CCU1 absolut korrekt. Zeigt alle Geräte und alles läßt sih konfigurieren.
Wenn ich wieder den rfd mit LAN Gateway laufen sehe ich im HM-Manager das LAN-Gateway, nur kann ich kein Gerät anleren. Habe auch so alles an Konfiguration durch was so geht (Binrpc, xmlrpc IP Adressen) und mehrmaligen Werksreset.
Der LAN Gateway kann (sollte) es auch nicht sein da er in der LXCCU problemlos funktioniert hat.
Die einzige unregelmäßigkeit die ich gefunden habe ist wie im Post vorher beschrieben (Firmware im HM-Manager 1.13 wärend der LAN Gateway aber 114. hat).

Was mir noch eingefallen ist : ich habe das Firmwareupdtae des LAN-Gateways  glaube ich über die LXCCU gemacht. Ich denke aber das sollte doch kein Problem darstellen.

Gruß Maik

**Comment by fortschritt311** [comment]
Hi.
Hat noch jemand eine Idee?

Gruß

**Comment by hobbyquaker** [comment]
Kam leider noch nicht dazu mich darum zu kümmern, sobald ich wieder Zeit für den HM-Manager finde schau ich mir das noch mal an.

**Comment by hobbyquaker** [comment]
Hallo Maik, ich schließe den Issue hier mal, ich gehe davon aus dass das eher ein Hmcon- als ein Homematic-Manager-Problem ist. Hmcon habe ich letzte Woche noch mal ein Update spendiert, würde Dich bitten es damit zu testen und ggf. bei Hmcon einen neuen Issue zu öffnen.
Viele Grüße,
Sebastian
