### ISSUE TITLE
Probleme mit wired-DV zwischen virtuellen Tastern und Ausgängen am HMW-IO-12-FM

### ISSUE THREAD

**Issue by Familienvater** [hobbyquaker/homematic-manager#33]
Neue, leere Verknüpfung lässt sich anlegen, aber es kommt kein Fenster, wo das Paramset etc. bearbeitet werden könnte.
Eine auf der CCU1 angelegte Verknüpfung kann auch nicht im HM-Manager angezeigt werden.
In der RPC-Konsole konnte ich das Paramset aber einmal abrufen, dann ist aber der HM-Manager abgeschmiert. Generell habe ich das Gefühl, das der Manager sehr wackelig ist, gibt es eine Methode, um die RPC-Connection sauber wieder bei der CCU abzumelden? Das syslog der CCU ist nach dem auch nach dem sauberen? Beenden mit "hm-manager stop" voll mit rfd: XmlRpc transport error, was bei der CCU1 über kurz oder lang einen Neustart der CCU1 erfordert.

**Comment by hobbyquaker** [comment]
Wired-DVs sind noch nicht richtig implementiert, steht auf der Todo (https://github.com/hobbyquaker/homematic-manager/issues/23).
RPC init wird beim Beenden des HM-Manager Server Prozesses sauber abgemeldet. Also im Zweifel einfach noch mal neu-starten und wieder beenden. Warum er gecrashed ist würde mich brennend interessieren, kannst Du versuchen das zu reproduzieren und das Logfile dazu posten?

**Comment by Familienvater** [comment]
Gerne, ich habe im Code gesehen, das es ein config.debug gibt, wo muss ich da was für eintragen, damit der Manager ggf. anfängt irgendwo irgendwas zu loggen?
Komme da aber eher nur am Wochenende dazu, weil ich die CCU1 ggf. im richtigen "Moment" auffangen muss, damit die nicht zu tief abstürzt. Die CCU1 ist gefühlt deutlich weniger verzeihend als die CCU2, zumindest was den hs485d angeht, der wird bei mir mit bis zum 120 Messages/Minute befeuert (Windsensor am Frequenzeingang, und diverse Analogeingänge).

**Comment by hobbyquaker** [comment]
In der config kannst Du das Attribut `debug: true` setzen und dann am besten nicht über hm-manager start starten sondern direkt auf der commandline (`node main.js` im hm-manager verzeichnis), dann bekommst die Ausgabe direkt auf die Console (Beenden dann via ctrl-c).

**Comment by Familienvater** [comment]
Hi, ging schneller als ich gedacht habe, wobei das wahrscheinlich ein anderer Fehler ist, ich habe mich jetzt gegen meine CCU2 verbunden gehabt, an der nur ein paar Testdevices hängen, davor hatte ich immer mit der Live-CCU1 getestet... Beim zweiten Start gegen die CCU2 war dann alles gut, und ich habe auch jedemenge Wired-Events durchgefeuert, das ging problemlos. Muss dann nachher doch noch mal mit der Live-CCU1 testen...
vm-linux:/usr/lib/node_modules/homematic-manager # node main.js
loadJson /root/.hm-manager/devices.json
loadJson /root/.hm-manager/paramsetDescriptions.json
loadJson /root/.hm-manager/names.json
webserver/socket.io listening on port 8081
xmlrpc server listening on 192.168.1.33:2015
RPC -> 192.168.1.11:2001 init http://192.168.1.33:2015 hmm_0
bin server already started
RPC -> 192.168.1.11:2000 init http://192.168.1.33:2015 hmm_1
RPC <- listDevices ["hmm_0"]
RPC -> listDevices response length 344
RPC <- listDevices ["hmm_1"]
RPC -> listDevices response length 202
RPC <- deleteDevices ["hmm_1",["LEQ0116086","LEQ0116086:0","LEQ0116086:1","LEQ0116086:2","LEQ0116086:3","LEQ0116086:4","LEQ0                           189797","LEQ0189797:0","LEQ0189797:1","LEQ0189797:10","LEQ0189797:11","LEQ0189797:12","LEQ0189797:2","LEQ0189797:3","LEQ0189                           797:4","LEQ0189797:5","LEQ0189797:6","LEQ0189797:7","LEQ0189797:8","LEQ0189797:9","LEQ0249518","LEQ0249518:0","LEQ0249518:1"                           ,"LEQ0249518:2","LEQ0249518:3","LEQ0251828","LEQ0251828:0","LEQ0251828:1","LEQ0251828:10","LEQ0251828:11","LEQ0251828:12","L                           EQ0251828:13","LEQ0251828:14","LEQ0251828:15","LEQ0251828:16","LEQ0251828:17","LEQ0251828:18","LEQ0251828:19","LEQ0251828:2"                           ,"LEQ0251828:20","LEQ0251828:21","LEQ0251828:22","LEQ0251828:23","LEQ0251828:24","LEQ0251828:25","LEQ0251828:26","LEQ0251828                           :3","LEQ0251828:4","LEQ0251828:5","LEQ0251828:6","LEQ0251828:7","LEQ0251828:8","LEQ0251828:9","LEQ0251901","LEQ0251901:0","L                           EQ0251901:1","LEQ0251901:10","LEQ0251901:11","LEQ0251901:12","LEQ0251901:13","LEQ0251901:14","LEQ0251901:15","LEQ0251901:16"                           ,"LEQ0251901:17","LEQ0251901:18","LEQ0251901:19","LEQ0251901:2","LEQ0251901:20","LEQ0251901:21","LEQ0251901:22","LEQ0251901:                           23","LEQ0251901:24","LEQ0251901:25","LEQ0251901:26","LEQ0251901:3","LEQ0251901:4","LEQ0251901:5","LEQ0251901:6","LEQ0251901:                           7","LEQ0251901:8","LEQ0251901:9","LEQ0979094","LEQ0979094:0","LEQ0979094:1","LEQ0979094:2","LEQ0979094:3","LEQ0979094:4","LE                           Q1004023","LEQ1004023:0","LEQ1004023:1","LEQ1004023:10","LEQ1004023:11","LEQ1004023:12","LEQ1004023:2","LEQ1004023:3","LEQ10                           04023:4","LEQ1004023:5","LEQ1004023:6","LEQ1004023:7","LEQ1004023:8","LEQ1004023:9","LEQ1181578","LEQ1181578:0","LEQ1181578:                           1","LEQ1181578:2","LEQ1181578:3","LEQ1181717","LEQ1181717:0","LEQ1181717:1","LEQ1181717:2","LEQ1181717:3","LEQ1181759","LEQ1                           181759:0","LEQ1181759:1","LEQ1181759:2","LEQ1181759:3","LEQ1181872","LEQ1181872:0","LEQ1181872:1","LEQ1181872:2","LEQ1181872                           :3","LEQ1182147","LEQ1182147:0","LEQ1182147:1","LEQ1182147:2","LEQ1182147:3","LEQ1184658","LEQ1184658:0","LEQ1184658:1","LEQ                           1184658:10","LEQ1184658:11","LEQ1184658:12","LEQ1184658:2","LEQ1184658:3","LEQ1184658:4","LEQ1184658:5","LEQ1184658:6","LEQ1                           184658:7","LEQ1184658:8","LEQ1184658:9","leq1182496","leq1182496:0","leq1182496:1","leq1182496:2","leq1182496:3","leq1182520                           ","leq1182520:0","leq1182520:1","leq1182520:2","leq1182520:3"]]
saveJson /root/.hm-manager/devices.json
    <- init response null ""
RPC <- newDevices ["hmm_1",[{"ADDRESS":"LEQ1004027","AVAILABLE_FIRMWARE":"3.00","CHILDREN":["LEQ10
saveJson /root/.hm-manager/devices.json
RPC <- deleteDevices ["hmm_0",["IEQ0044789","IEQ0044789:0","IEQ0044789:1","IEQ0046367","IEQ0046367:0","IEQ0046367:1","IEQ040                           4060","IEQ0404060:0","IEQ0404060:1","IEQ0547300","IEQ0547300:0","IEQ0547300:1","JEQ0000162","JEQ0000162:0","JEQ0000162:1","J                           EQ0015973","JEQ0015973:0","JEQ0015973:1","JEQ0029718","JEQ0029718:0","JEQ0029718:1","JEQ0030043","JEQ0030043:0","JEQ0030043:                           1","JEQ0034152","JEQ0034152:0","JEQ0034152:1","JEQ0115432","JEQ0115432:0","JEQ0115432:1","JEQ0115441","JEQ0115441:0","JEQ011                           5441:1","JEQ0115449","JEQ0115449:0","JEQ0115449:1","JEQ0144467","JEQ0144467:0","JEQ0144467:1","JEQ0144467:10","JEQ0144467:11                           ","JEQ0144467:12","JEQ0144467:13","JEQ0144467:14","JEQ0144467:15","JEQ0144467:16","JEQ0144467:2","JEQ0144467:3","JEQ0144467:                           4","JEQ0144467:5","JEQ0144467:6","JEQ0144467:7","JEQ0144467:8","JEQ0144467:9","JEQ0156711","JEQ0156711:0","JEQ0156711:1","JE                           Q0156711:2","JEQ0156711:3","JEQ0196095","JEQ0196095:0","JEQ0196095:1","JEQ0196095:2","JEQ0196095:3","JEQ0646560","JEQ0646560                           :0","JEQ0646560:1","JEQ0646560:2","JEQ0646560:3","JEQ0646560:4","JEQ0651409","JEQ0651409:0","JEQ0651409:1","JEQ0654661","JEQ                           0654661:0","JEQ0654661:1","JEQ0654661:2","JEQ0654661:3","JEQ0684911","JEQ0684911:0","JEQ0684911:1","JEQ0684911:2","JEQ068491                           1:3","JEQ0684911:4","JEQ0720472","JEQ0720472:0","JEQ0720472:1","JEQ0738898","JEQ0738898:0","JEQ0738898:1","JEQ0739006","JEQ0                           739006:0","JEQ0739006:1","KEQ0023960","KEQ0023960:0","KEQ0023960:1","KEQ0023960:2","KEQ0034867","KEQ0034867:0","KEQ0034867:1                           ","KEQ0035066","KEQ0035066:0","KEQ0035066:1","KEQ0121890","KEQ0121890:0","KEQ0121890:1","KEQ0175303","KEQ0175303:0","KEQ0175                           303:1","KEQ0508861","KEQ0508861:0","KEQ0508861:1","KEQ0508861:2","KEQ0508861:3","KEQ0508861:4","KEQ0508861:5","KEQ0508861:6"                           ,"KEQ0515363","KEQ0515363:0","KEQ0515363:1","KEQ0515363:2","KEQ0515363:3","KEQ0515363:4","KEQ0515363:5","KEQ0515363:6","KEQ0                           515639","KEQ0515639:0","KEQ0515639:1","KEQ0515639:2","KEQ0515639:3","KEQ0515639:4","KEQ0515639:5","KEQ0515639:6","KEQ0543623                           ","KEQ0543623:0","KEQ0543623:1","KEQ0543623:2","KEQ0543623:3","KEQ0543623:4","KEQ0543623:5","KEQ0543668","KEQ0543668:0","KEQ                           0543668:1","KEQ0543668:2","KEQ0543668:3","KEQ0543668:4","KEQ0543668:5","KEQ0800143","KEQ0800143:0","KEQ0800143:1","KEQ084691                           2","KEQ0846912:0","KEQ0846912:1","KEQ0847496","KEQ0847496:0","KEQ0847496:1","KEQ1005927","KEQ1005927:0","KEQ1005927:1","KEQ1                           005927:2","KEQ1005927:3","LEQ0002558","LEQ0002558:0","LEQ0002558:1","LEQ0002558:2","LEQ0002558:3","LEQ0002558:6","LEQ0002558                           :7","LEQ0079098","LEQ0079098:0","LEQ0079098:1","LEQ0079098:2","LEQ0079098:3","LEQ0079098:6","LEQ0079098:7","LEQ0081714","LEQ                           0081714:0","LEQ0081714:1","LEQ0081714:2","LEQ0081714:3","LEQ0081714:6","LEQ0081714:7","LEQ0143053","LEQ0143053:0","LEQ014305                           3:1","LEQ0184432","LEQ0184432:0","LEQ0184432:1","LEQ0184432:2","LEQ0184432:3","LEQ0184432:4","LEQ0184432:5","LEQ0184432:6","                           LEQ0272444","LEQ0272444:0","LEQ0272444:1","LEQ0272444:2","LEQ0272444:3","LEQ0272444:4","LEQ0272444:5","LEQ0272444:6","LEQ027                           3030","LEQ0273030:0","LEQ0273030:1","LEQ0273030:2","LEQ0273030:3","LEQ0273030:4","LEQ0273030:5","LEQ0273030:6","LEQ0273117",                           "LEQ0273117:0","LEQ0273117:1","LEQ0273117:2","LEQ0273117:3","LEQ0273117:4","LEQ0273117:5","LEQ0273117:6","LEQ0282476","LEQ02                           82476:0","LEQ0282476:1","LEQ0473866","LEQ0473866:0","LEQ0473866:1","LEQ0569930","LEQ0569930:0","LEQ0569930:1","LEQ0569930:2"                           ,"LEQ0888190","LEQ0888190:0","LEQ0888190:1","LEQ1033692","LEQ1033692:0","LEQ1033692:1","LEQ1033705","LEQ1033705:0","LEQ10337                           05:1","LEQ1278325","LEQ1278325:0","LEQ1278325:1","LEQ1278729","LEQ1278729:0","LEQ1278729:1","LEQ1278790","LEQ1278790:0","LEQ                           1278790:1","LEQ1283399","LEQ1283399:0","LEQ1283399:1","LEQ1283399:2","LEQ1283399:3","LEQ1283399:6","LEQ1283399:7","MEQ000748                           3","MEQ0007483:0","MEQ0007483:1","MEQ0007483:2","MEQ0007483:3","MEQ0007483:4","MEQ0007483:5","MEQ0007483:6","MEQ0024943","ME                           Q0024943:0","MEQ0024943:1","MEQ0024943:2","MEQ0180735","MEQ0180735:0","MEQ0180735:1","MEQ0180735:2","MEQ0180735:3","MEQ01807                           35:6","MEQ0180735:7","MEQ0180808","MEQ0180808:0","MEQ0180808:1","MEQ0180808:2","MEQ0180808:3","MEQ0180808:6","MEQ0180808:7",                           "MEQ0180845","MEQ0180845:0","MEQ0180845:1","MEQ0180845:2","MEQ0180845:3","MEQ0180845:6","MEQ0180845:7","MEQ0180868","MEQ0180                           868:0","MEQ0180868:1","MEQ0180868:2","MEQ0180868:3","MEQ0180868:6","MEQ0180868:7"]]
saveJson /root/.hm-manager/devices.json
RPC <- newDevices ["hmm_0",[{"ADDRESS":"LEQ0250464","CHILDREN":["LEQ0250464:0","LEQ0250464:1","LEQ
saveJson /root/.hm-manager/devices.json
    <- init response null ""
RPC <- event ["hmm_0","LEQ0250464:0","UNREACH",true]
RPC <- event ["hmm_0","LEQ0575095:0","UNREACH",true]
RPC -> ping ccu1-rf 29185
events.js:142
    throw TypeError('listener must be a function');
          ^
TypeError: listener must be a function
    at TypeError (native)
    at ClientRequest.addListener (events.js:142:11)
    at Client.methodCall (/usr/lib/node_modules/homematic-manager/node_modules/homematic-xmlrpc/lib/client.js:117:11)
    at pingPong (/usr/lib/node_modules/homematic-manager/main.js:93:36)
    at wrapper [as _onTimeout] (timers.js:274:14)
    at Timer.listOnTimeout (timers.js:119:15)

**Comment by hobbyquaker** [comment]
ok, i see. Darf auf jeden Fall nicht sein ;-) Kümmere mich asap darum, Grüße, Sebastian

**Comment by Familienvater** [comment]
Hi, der ping war im Zweifelsfall auch der Spielverderber beim Live-System mit der CCU1, da ist er zumindest auch nach kurzer Zeit mit ausgestiegen.

Christian

**Comment by Blindfox** [comment]
Hallo hobbyquaker, ich glaube ich habe evt das selbe Problem wie Familienvater.
In unregelmässigen Abständen semmelt der Dienst ab ("disconnected").
Ich habe keine CCU, nur 5x LAN-CFG.
Ich habe mal das Log aktiviert wie von Dir empfohlen. folgendes kam dabei raus:

![2015-12-17 22_49_18-hm-manager](https://cloud.githubusercontent.com/assets/16342535/11883041/7ce46fec-a510-11e5-9049-594966e59778.jpg)

Sieht man da schon was?
Gruß Blindfox
