### ISSUE TITLE
Service message popup

### ISSUE THREAD

**Issue by trilu2000** [hobbyquaker/homematic-manager#34]
Hallo, zuerst einmal vielen Dank für das tolle Stück Software. Ich betreibe den Homematic Manager im Zusammenhang mit Homegear auf einem OrangePI. Das Einzige was mich derzeit stört, bzw nervt - immer wenn Homegear ein Ereignis sendet, bekomme ich in der Homematic Manager Oberfläche ein Popup mit dem Ereignis angezeigt. Mit wenigen Devices ist das nicht weiter schlimm, aber je mehr Devices und damit potentiell Ereignissen wird es doch recht nervig...
Gibt es irgendeine Config Datei in der man die Popups abschalten kann?

Viele Grüße
Horst

**Comment by hobbyquaker** [comment]
Was für Ereignisse sind das? Keine von Homematic Geräten, oder?

**Comment by JanLochi** [comment]
Kann ich bestätigen. Siehe Bild:
![screen1](https://cloud.githubusercontent.com/assets/6726808/12494933/287186d2-c08d-11e5-8f38-1f46be73ebfd.png)

**Comment by dancer7162** [comment]
Auch mir hat die Software schon oft gute Dienste geleistet, Danke dafür.
Das bemängelte Verhalten der automatischen Popus war für mich mit  zunehmender Anzahl von (Homematic) Devices ebenfalls ein Problem. 

Anbei ein Patch der das Problem bei mir löst.
Dazu bitte noch in der Konfigurationsdatei hm-manager.json den Eintrag
     "enableDialogPopup":"false"
aufnehmen.

Viele Grüße
Ralf

[enableDialogPopup.patch.zip](https://github.com/hobbyquaker/homematic-manager/files/120233/enableDialogPopup.patch.zip)

**Comment by hobbyquaker** [comment]
Hallo, in Version 1.0.12 sollten diese Popups nur noch für "echte" Service-Meldungen erscheinen (UNREACH, LOWBAT, CONFIG_PENDING, ...) - ich denke da machen Sie auch Sinn.

@dancer7162 Habe das mit der config-Option nun auch eingebaut, allerdings mit umgekehrter Logik, mit der Config Option `"disableServiceMsgPopup": true` kann man nun das Popup komplett abschalten. https://github.com/hobbyquaker/homematic-manager/commit/9f09cf2ddfd21ae0db53aef6453a4f336e29fd97

Grüße,
Sebastian

**Comment by leifbladt** [comment]
:+1:

**Comment by trilu2000** [comment]
Vielen Dank!!!!!!!!!!!!
