### ISSUE TITLE
Device Firmware-Update schon implementiert?

### ISSUE THREAD

**Issue by ploebb** [hobbyquaker/homematic-manager#37]
Ich kann zwar auf den Button "Firmware Update" klicken, aber er lädt keine Firmware auf die Geräte:
"Unable to load updatefile (-1)" 

Muss ich die Firmware-Datei irgendwo hochladen/ablegen?

Oder ist diese Funktion schlicht noch nicht implementiert?

**Comment by hobbyquaker** [comment]
Ist implementiert, aber das wird nur funktionieren wenn dem Schnittstellenprozess ein Update-File vorliegt und der Aktor/Sensor "OTAU" fähig ist (sind nur wenige neue, z.B. der HM-CC-RT-DN). Der rfd kennt zwei Config-Optionen für Firmware-Verzeichnisse: `Firmware Dir`und `User Firmware Dir`. In ersterem liegen Firmware-Files die eQ3 mit dem Schnittstellenprozess bereits mitgeliefert hat, in Zweiterem kann man solche ablegen die man manuell von http://eq-3.de heruntergeladen hat.

**Comment by ploebb** [comment]
Sehr cool! Danke für die Info! Dann werd ich mich mal schlau machen ob der unterstützen Geräte und das ggf mal ausprobieren.
