### ISSUE TITLE
Verknüpfung erzeugen

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/homematic-manager#39]
Verknüpfung anlegen funktioniert seit 1.0.14 nicht mehr.

**Comment by fortschritt311** [comment]
Hi Sebastian,
wirst du dem HM-Manager dazu noch ein Update spendieren?
Habe jetzt HMCON mit dem HS485D soweit eingerichtet und am laufen, und würde gerne komplett umstellen (endlich die CCU1 loswerden). Dazu müßten aber die Verknüpfungen funktionieren.

Das bisschen was ich an Funk laufen habe, da würde ich noch die CCU1 als Gateway nutzen, bis zum RFD-Update durch EQ3.

Viele Grüße
Maik

**Comment by hobbyquaker** [comment]
Kann gerade nicht versprechen wann, aber ein `sudo npm install -g homematic-manager@1.0.13` sollte als vorläufiger Workaround gehen. Eventuell kam der Fehler auch schon mit der 1.0.13, da bin ich gerade nicht sicher, dann eben die 1.0.12 installieren.

**Comment by fortschritt311** [comment]
Super, die 1.0.12 hat funktioniert. Verknüpfungen können angelegt werden.
Die 1.0.13 ist in den Quellen nicht vorhanden meint npm.
Wired Geräte kann ich dann ja auf der RPC-Konsole mit searchDevice hinzufügen.

Danke für den Hinweis.
Ihr leistet hier eine hervorragende Arbeit. Auch mqtt ist echt scharf :-)
