### ISSUE TITLE
Keine Geräte und Absturz wenn Verknüpfungen angeclickt wird

### ISSUE THREAD

**Issue by avanc** [hobbyquaker/homematic-manager#42]
Ich bekomme keine Informationen im hm-manager angezeigt (z.B. keine Geräte). Lediglich im Reiter Verknüpfungen wird was angzeigt. Wenn ich dort auf ein Device clicke, stürzt hm-manager jedoch ab.

1.0.14:
-------

Fehlermeldung Webinterface:

    RF getLinkInfo {"code":-1,"faultCode":-1,"faultString":"Type error."}

Fehlermeldung in Console:

    var dev = localDevices[daemon][params[0]];
                                          ^
    TypeError: Cannot read property 'null' of undefined
        at rpcProxy (/home/klomp/tmp/homematic/node_modules/homematic-manager/main.js:304:43)
        at Socket.<anonymous> (/home/klomp/tmp/homematic/node_modules/homematic-manager/main.js:286:25)
        at Socket.emit (events.js:106:17)
        at /home/klomp/tmp/homematic/node_modules/homematic-manager/node_modules/socket.io/lib/socket.js:503:12
        at process._tickCallback (node.js:448:13)

1.0.12:
-------

Fehlermeldung Webinterface:

    disconnect

**Comment by hobbyquaker** [comment]
fixed in v2
