### ISSUE TITLE
hmIP aus dem OCCU

### ISSUE THREAD

**Issue by pvizeli** [hobbyquaker/homematic-manager#56]
Ich arbeite gerade an einem Add-on für Homematic Centrale als Hass.io Add-on (https://github.com/home-assistant/hassio-addons/pull/209).

Ich weiss, dass es ein overlay Treiber braucht um die nötigen devices zu erstellen. Was braucht es sonst noch aus dem OCCU damit homematic-manager mit den hmIP devices funktionieren kann?

Vielleicht kann mir jemand einige Inputs liefern, dass wäre super. Danke

**Comment by ch-world** [comment]
Hast du dir mal https://github.com/leonsio/YAHM angesehen? Ich setze das momentan Produktiv mit HmIP Devices ein. Ich hatte auch mit dem Gedanken gespielt einen HmIP fähigen Docker-Container zu erstellen, hatte aber bisher nicht die Zeit dafür.

**Comment by hobbyquaker** [comment]
Hi, ich schließe den Issue mal, ist ja nicht direkt ein hm-manager ding. Zur Frage nach dem Overlay treiber am besten mal direkt bei occu/yahm/piVCCU nachfragen.
