### ISSUE TITLE
HTML in Grids gets escaped

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/homematic-manager#57]
instead of icons and buttons html code is shown... 
Issue affects the build only, doesn't occur in debug mode.

**Comment by ch-world** [comment]
You're using an old version of jqGrid in your dev environment. In starting with free-jqgrid 4.15 they activated auto escaping of values. I fixed temporarily by adding:

`jQuery.extend(jQuery.jgrid.defaults,` { autoencode: false });

**Comment by hobbyquaker** [comment]
Thx for the hint! 👍
