### ISSUE TITLE
Verknüpfung kann nicht bearbeitet werden

### ISSUE THREAD

**Issue by Poquaruse** [hobbyquaker/homematic-manager#58]
Hi,

danke für's Erstellen dieses hilfreichen Tools! 
Leider ist es mir nicht möglich, eine Verknüpfung anzuschauen/zu bearbeiten. Beim Versuch, eine Verknüpfung zu bearbeiten (Rechtsklick oder Zahnrad unten) erscheint blau hinterlegt "Ladevorgang..." und nichts passiert. Die Simulation eines kurzen Tastendrucks funktioniert hingegen einwandfrei!

Leider weiß ich nicht, wie ich beim Debuggen helfen könnte, versuche aber gerne behilflich zu sein!

Version: 2.0.0beta3, kompilierte Exe unter Windows 8.1

Danke schonmal im Voraus!

**Comment by anli-xsigns** [comment]
Moin,

schau bitte mal in der Entwicklerkonsole Deines Browsers (F12 in Chrome), ob dort Javascript Fehler auftauchen und poste diese hier. Danke.

 

Von: Poquaruse <notifications@github.com> 
Gesendet: Samstag, 17. März 2018 22:50
An: hobbyquaker/homematic-manager <homematic-manager@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [hobbyquaker/homematic-manager] Verknüpfung kann nicht bearbeitet werden (#58)

 

Hi,

danke für's Erstellen dieses hilfreichen Tools!
Leider ist es mir nicht möglich, eine Verknüpfung anzuschauen/zu bearbeiten. Beim Versuch, eine Verknüpfung zu bearbeiten (Rechtsklick oder Zahnrad unten) erscheint blau hinterlegt "Ladevorgang..." und nichts passiert. Die Simulation eines kurzen Tastendrucks funktioniert hingegen einwandfrei!

Leider weiß ich nicht, wie ich beim Debuggen helfen könnte, versuche aber gerne behilflich zu sein!

Version: 2.0.0beta3.

Danke schonmal im Voraus!

**Comment by Poquaruse** [comment]
Hi, 

danke für die schnelle Antwort! 
Zwar hatte ich es direkt reineditiert, aber in die Mail ist es logischerweise nicht gelangt: ich verwende die kompilierte Exe-Version unter Windows 8.1 (2.0.0beta3). In dem Programm konnte ich keine Konsole finden (F-Tasten ergeben zumindest auch mal nichts...)

Viele Grüße

**Comment by hobbyquaker** [comment]
Was sind das für Geräte/Kanäle die da verknüpft sind?

**Comment by Poquaruse** [comment]
Rollladenaktoren und 6-fach-Taster bspw. Auch ein paar virtuelle Taster. Keine der Verknüpfungen lässt sich öffnen, alle zeigen dasselbe Problem.

**Comment by hobbyquaker** [comment]
Versuch es bitte noch mal mit der 2.0.0-beta.6 - habe was eingebaut damit eventuelle Fehler in einem Popup angezeigt werden, falls das passiert bitte mal ein Screenshot von dem Popup hier posten.

**Comment by Poquaruse** [comment]
Hi,

da taucht tatsächlich ein Fehler auf:

Unhandled Error
TypeError: Cannot read property 'TYPE' of undefined
    at listLinks.forEach.link (C:/Users/<USER>/AppData/Local/Programs/homematic-manager/resources/app.asar/www/js/homematic-manager.js:2556:39)
    at Array.forEach (<anonymous>)
    at dialogLinkparamset (C:/Users/<USER>/AppData/Local/Programs/homematic-manager/resources/app.asar/www/js/homematic-manager.js:2549:15)
    at rpcAlert (C:/Users/<USER>/AppData/Local/Programs/homematic-manager/resources/app.asar/www/js/homematic-manager.js:3096:25)
    at ipcRpc.send (C:/Users/<USER>/AppData/Local/Programs/homematic-manager/resources/app.asar/www/js/homematic-manager.js:3929:13)
    at EventEmitter.Rpc.ipc.on (C:/Users/<USER>/AppData/Local/Programs/homematic-manager/resources/app.asar/node_modules/electron-ipc-rpc/index.js:26:17)

Ich hoffe, das hilft weiter!

Viele Grüße

**Comment by hobbyquaker** [comment]
Hab eben die 2.0.0-beta.7 gebaut, versuch mal ob Du damit Deine Verknüpfungen editieren kannst.

**Comment by hobbyquaker** [comment]
na dann auf ein Neues ;-) Hab eben die 2.0.0-beta.8 gebaut.

**Comment by nicx** [comment]
super, jetzt funktionieren die Direktverknüpfungen bei mir ohne Fehlermeldung 👍

**Comment by Poquaruse** [comment]
Sorry für die späte Antwort, bin jetzt erst dazu gekommen. Funktioniert wunderbar! :+1: Vielen Dank!
